# openjdk-1.8.0 dockerfile

FROM centos:7.9.2009
USER root

RUN yum clean all && yum install -y java-1.8.0-openjdk.x86_64 && rm -rf /var/cache/yum/*

ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0-openjdk
ENV PATH $PATH:$JAVA_HOME/bin

