# test dockerfile
#   docker build --rm -t test .   
#   docker run -it test /bin/bash   

FROM centos:7.9.2009 
USER root

ENV JAVA_HOME /usr/java/default

ADD README.md /README.md

RUN echo 'hello world!' > /hellotest

CMD date >>/uptime

